[build]
  # directory located at the absolute path "root/project/build-output"
  publish = "build"
  # Default build command.
  command = "npm run build"
[functions]
  # Directory with serverless functions, including background functions,
  # to deploy. This is relative to the base directory if one has been set,
  # or the root directory if a base hasn’t been set.
  directory = "functions/"
# more at: https://docs.netlify.com/configure-builds/file-based-configuration/
